---
- name: Determine install method
  block:
    - name: Set install method for apt
      when: syncthing_install_method == "" and ansible_facts['pkg_mgr'] == "apt"
      ansible.builtin.set_fact:
        syncthing_install_method: apt

    - name: Set install method for generic package manager
      when: syncthing_install_method == ""
      ansible.builtin.set_fact:
        syncthing_install_method: generic

- debug:
    var: syncthing_install_method

- ansible.builtin.include_tasks: install.{{ syncthing_install_method }}.yaml
- ansible.builtin.include_tasks: service.{{ ansible_service_mgr }}.yaml
- ansible.builtin.include_tasks: service_config.yaml
