---
# This wait is required on first install and enabling of the service to ensure the config file is available to be modified.
- name: Wait until config file exists
  loop: "{{ syncthing_instances }}"
  loop_control:
    label: "{{ item.username }}"
  become: true
  become_user: "{{ item.username }}"
  ansible.builtin.wait_for:
    state: present
    path: ~/.local/state/syncthing/config.xml
    timeout: 30

# Configure Web UI first as we need to use the API to retrieve the Device ID. This can't be done if the port conflicts with another instance.
- name: Set Web UI address
  loop: "{{ syncthing_instances }}"
  loop_control:
    label: "{{ item.username }}"
  become: true
  become_user: "{{ item.username }}"
  community.general.xml:
    path: ~/.local/state/syncthing/config.xml
    xpath: /configuration/gui/address
    value: "{{ item.syncthing_config.web_ui.listen_ip | default('127.0.0.1') }}:{{ item.syncthing_config.web_ui.port | default(8384) }}"
  notify:
    - Restart syncthing services

- name: Set Web UI username
  loop: "{{ syncthing_instances }}"
  loop_control:
    label: "{{ item.username }}"
  become: true
  become_user: "{{ item.username }}"
  community.general.xml:
    path: ~/.local/state/syncthing/config.xml
    xpath: /configuration/gui/user
    value: "{{ item.syncthing_config.web_ui.auth.username | default(item.username) | default('') }}"
  notify:
    - Restart syncthing services

- name: Set Web UI password
  loop: "{{ syncthing_instances }}"
  loop_control:
    label: "{{ item.username }}"
  become: true
  become_user: "{{ item.username }}"
  community.general.xml:
    path: ~/.local/state/syncthing/config.xml
    xpath: /configuration/gui/password
    value: "{{ item.syncthing_config.web_ui.auth.password_hash | default('') }}"
  notify:
    - Restart syncthing services

- name: Determine Device ID
  block:
    # Flush handlers to ensure any port changes have taken effect
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
    - name: Wait for syncthing services to start
      loop: "{{ syncthing_instances }}"
      loop_control:
        label: "{{ item.username }}"
      ansible.builtin.wait_for:
        port: "{{ item.syncthing_config.web_ui.port | default(8384) }}"
        timeout: 30
    - name: Make request to Syncthing Web UI to retrieve Device ID
      loop: "{{ syncthing_instances | map(attribute='username') }}" # Have to loop by username for items2dict in set_fact to work
      loop_control:
        label: "{{ item }}"
      ansible.builtin.uri:
        url: "http://localhost:{{ (syncthing_instances | selectattr('username', 'eq', item))[0].syncthing_config.web_ui.port | default(8384) }}/"
      check_mode: false
      register: syncthing_webui_request
    - name: Build Device ID dictionary
      set_fact:
        syncthing_instance_device_ids: "{{ syncthing_webui_request.results | items2dict(key_name='item', value_name='x_syncthing_id') }}"
