---
- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Restart systemd services
  listen: Restart syncthing services
  when: ansible_service_mgr == "systemd"
  loop: "{{ syncthing_instances }}"
  loop_control:
    label: "{{ item.username }}"
  ansible.builtin.systemd_service:
    name: syncthing@{{ item.username }}
    state: restarted
